---
# Tasks for HAProxy role
- name: Print messages
  ansible.builtin.import_tasks: ../../../shared_tasks/print_messages.yml

- name: Add HAProxy stable repository from PPA and install its signing key on Ubuntu target
  ansible.builtin.apt_repository:
    repo: ppa:vbernat/haproxy-2.6
  tags:
    - "{{ app }}"

- name: Install HAProxy
  ansible.builtin.apt:
    name: haproxy
    state: latest
    only_upgrade: true
    update_cache: true
  notify: Restart HAProxy
  tags:
    - "{{ app }}"

- name: Configure haproxy.cfg file
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify: Restart HAProxy
  tags:
    - "{{ app }}"

- name: Check HAProxy is active
  ansible.builtin.systemd:
    name: haproxy
    state: started
    enabled: true
  notify: Restart HAProxy
  tags:
    - "{{ app }}"
