---
services:
  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:1.1.0
    restart: always
    ports:
      - "9113:9113"
    command: ["--nginx.scrape-uri=http://localhost:80/status"]
