---
- name: Print startup messages
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop:
    - "{{ initial_message }}"
    - "{{ startup_message }}"
  changed_when: false
  run_once: true
  delegate_to: localhost
  tags:
    - "{{ app }}"
