---
# Tasks for HAProxy role
- name: Print messages
  ansible.builtin.import_tasks: ../../../shared_tasks/print_messages.yml

- name: Add HAProxy stable repository from PPA and install its signing key on Ubuntu target
  ansible.builtin.apt_repository:
    repo: ppa:vbernat/haproxy-2.6

- name: Install HAProxy
  ansible.builtin.apt:
    name: haproxy
    state: present
    update_cache: true
  notify: Restart HAProxy

- name: Configure haproxy.cfg file
  ansible.builtin.template:
    src: templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify: Restart HAProxy

- name: HAProxy service start
  ansible.builtin.service:
    name: haproxy
    state: restarted
  notify: Restart HAProxy
