#!/bin/bash
echo "Enter your age:"
read age
if [ $age -lt 30 ]; then
	echo "You're young!"
else
	echo "You're old!"
fi
echo "Enter your name:"
read name
echo "Your name is $name!"
echo "Nice to meet you $name"
