---
- name: Extend LVM Volume
  hosts: rke
  gather_facts: true
  become: true

  tasks:
    - name: Create physical volume
      command: pvcreate /dev/sdb

    - name: Extend volume group
      command: vgextend ubuntu-vg /dev/sdb

    - name: Extend logical volume
      command: lvextend -l +100%FREE /dev/ubuntu-vg/ubuntu-lv

    - name: Resize filesystem
      command: resize2fs -p /dev/mapper/ubuntu--vg-ubuntu--lv
