---
# playbook.yml
- name: Playbook for running different roles
  hosts: rke-cluster
  become: true
  vars:
    roles_to_run:
      initial: true
      docker: false
      node-exporter: false
      elasticsearch: false
      vector: false

  tasks:
    - name: Include roles based on conditions
      ansible.builtin.include_role:
        name: "{{ role_item.key }}"
      loop: "{{ roles_to_run | dict2items }}"
      loop_control:
        loop_var: role_item
      vars:
        app: "{{ role_item.key }}"
      when: role_item.value
