---
- name: Update all packeges on Linux servers

- hosts: ubuntu
  become: true

  tasks:
    - name: Update all packages on Ubuntu servers
      apt:
        name: "*"
        state: latest
        update_cache: True

- hosts: oracle
  become: true

  tasks:
    - name: Update all packages RHEL-like servers
      dnf:
        name: "*"
        state: latest
        update_cache: True
