---
# roles/initial/vars/main.yml
ansible_user: "zoubkovvv"
ansible_public_key: "{{ lookup('file', 'files/id_rsa.pub') }}"
disable_swap: false
enable_ssh_tcp_forwarding: true
journalctl_max_disk_usage: 1G
sshd_config_file: /etc/ssh/sshd_config
timezone: Asia/Yekaterinburg
update_packages: true
#rke: false
useful_packages:
  - apt-transport-https
  - bash-completion
  - ca-certificates
  - chrony
  - curl
  - git
  - gnupg
  - gnupg-agent
  - htop
  - jq
  - lsof
  - make
  - mc
  - net-tools
  - software-properties-common
  - sysstat
  - tree
  - unzip
  - vim
  - wget
  - zip

useless_packages:
  - unattended-upgrades
  - sosreport
  - apport
# - cloud-init
# - snapd
