# roles/initial/vars/main.yml
ansible_user: "zoubkovvv"
ansible_public_key: "{{ lookup('file', 'files/id_rsa.pub') }}"
useful_packages:
  - apt-transport-https
  - ca-certificates
  - chrony
  - curl
  - gnupg-agent
  - gnupg
  - htop
  - software-properties-common
  - tree
  - wget
update_packages: false
