---
# roles/initial/vars/main.yml
ansible_user: "zoubkovvv"
ansible_public_key: "{{ lookup('file', 'files/id_rsa.pub') }}"
useful_packages:
  - apt-transport-https
  - ca-certificates
  - chrony
  - curl
  - git
  - gnupg
  - gnupg-agent
  - htop
  - jq
  - lsof
  - make
  - mc
  - software-properties-common
  - sysstat
  - tree
  - unzip
  - vim
  - wget
  - zip
update_packages: true
