---
# vars file for docker
arch_mapping:  # Map ansible architecture {{ ansible_architecture }} names to Docker's architecture names
  x86_64: amd64
  aarch64: arm64
docker_user: zoubkovvv
docker_url: https://download.docker.com/linux/ubuntu
keyrings_folder: /etc/apt/keyrings
docker_old_packages:
  - docker.io
  - docker-doc
  - docker-compose
  - docker-compose-v2
  - podman-docker
  - containerd
  - runc

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

