---
# roles/initial/tasks/hostname.yml
# host's tasks for initial role
- name: Tasks with hostname
  block:
    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}.{{ domain_name }}"
        use: systemd

    - name: Ensure /etc/hostname is updated
      ansible.builtin.lineinfile:
        path: /etc/hostname
        line: "{{ inventory_hostname }}.{{ domain_name }}"
        backup: true

    - name: Ensure /etc/hosts is updated
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1'
        line: "127.0.1.1 {{ inventory_hostname }} {{ inventory_hostname }}.{{ domain_name }}"
        backup: true

  tags:
    - hostname

  rescue:
    - name: Handle failure
      debug:
        msg: "One or more apt update tasks failed."

# - name: Add or update /etc/hosts entry
#   ansible.builtin.lineinfile:
#     path: /etc/hosts
#     state: present
#     regexp: "^{{ hostvars[item].ansible_host }} "
#     line: "{{ hostvars[item].ansible_host }} {{ item }}"
#     backup: true
#   loop: "{{ groups['all'] }}"  
