---
# Tasks for initial role
- name: Print startup messages
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop:
    - "{{ initial_message }}"
    - "{{ startup_message }}"
  tags:
    - initial_role

- name: Ensure the user exists
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    state: present
    create_home: true
  tags:
    - initial_role

- name: Add SSH key to the user's authorized_keys
  ansible.builtin.authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ ansible_public_key }}"
    state: present
  tags:
    - initial_role

- name: Update package cache and install useful packages
  ansible.builtin.apt:
    name: "{{ useful_packages }}"
    state: latest
    update_cache: true
    cache_valid_time: 3600
  tags:
    - initial_role

- name: Update all packages
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true
    cache_valid_time: 3600
    autoclean: true
    autoremove: true
  tags:
    - initial_role
  when: update_packages

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
    use: systemd
  tags:
    - initial_role
    - set_hostname

- name: Ensure /etc/hostname is updated
  ansible.builtin.lineinfile:
    path: /etc/hostname
    line: "{{ inventory_hostname }}"
    create: true
  tags:
    - initial_role
    - set_hostname

- name: Ensure /etc/hosts is updated
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1 {{ inventory_hostname }}"
    create: true
  tags:
    - initial_role
    - set_hostname


- name: Add or update /etc/hosts entry
  ansible.builtin.lineinfile:
    path: /etc/hosts
    state: present
    regexp: "^{{ hostvars[item].ansible_host }} "
    line: "{{ hostvars[item].ansible_host }} {{ item }}"
    backup: true
  loop: "{{ groups['rancher'] }}"
      #- name: Display ansible_hostname
      #  debug:
      #    msg: "ansible-hostname is {{ansible_hostname}}"
      #- name: Add or update /etc/hosts entry
      #  ansible.builtin.lineinfile:
      #path: /etc/hosts
      #state: present
      #regexp: "^{{ item.ansible_host }} "
      #line: "{{ item.ansible_host }} {{ item.inventory_hostname }}"
      #loop: "{{ ansible_play_batch }}"
      #tags:
      #- initial_role
      #- add_host

