---
# Tasks for initial role
- name: Print startup messages
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop:
    - "{{ initial_message }}"
    - "{{ startup_message }}"
  tags:
    - initial_role

- name: Ensure the user exists
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: present
    create_home: true
    groups: sudo
    append: true
  tags:
    - initial_role

- name: Add sudoers file for user
  ansible.builtin.copy:
    dest: /etc/sudoers.d/{{ ansible_user }}
    content: "{{ ansible_user }} ALL=(ALL:ALL) NOPASSWD: ALL"
    owner: root
    group: root
    mode: '0440'
    backup: true
  tags:
    - initial_role
    - sudoers
  notify:
    - Validate sudoers file

- name: Add SSH key to the user's authorized_keys
  ansible.builtin.authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ ansible_public_key }}"
    state: present
  tags:
    - initial_role

- name: Set timezone to "{{ timezone  }}"
  community.general.timezone:
    name: "{{ timezone  }}"
  tags:
    - initial_role
    - timezone

- name: Update package cache and install useful packages
  ansible.builtin.apt:
    name: "{{ useful_packages }}"
    state: latest
    update_cache: true
    cache_valid_time: 3600
  tags:
    - initial_role

- name: Update all packages
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true
    cache_valid_time: 3600
    autoclean: true
    autoremove: true
  tags:
    - initial_role
  when: update_packages

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
    use: systemd
  tags:
    - initial_role
    - set_hostname

- name: Ensure /etc/hostname is updated
  ansible.builtin.lineinfile:
    path: /etc/hostname
    line: "{{ inventory_hostname }}"
    create: true
  tags:
    - initial_role
    - set_hostname

- name: Ensure /etc/hosts is updated
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1 {{ inventory_hostname }}"
    create: true
  tags:
    - initial_role
    - set_hostname

- name: Add or update /etc/hosts entry
  ansible.builtin.lineinfile:
    path: /etc/hosts
    state: present
    regexp: "^{{ hostvars[item].ansible_host }} "
    line: "{{ hostvars[item].ansible_host }} {{ item }}"
    backup: true
  loop: "{{ groups['rke'] }}"

- name: Disable SWAP
  shell: |
    swapoff -a
  tags:
    - initial_role
    - disable_swap
  when: disable_swap

- name: Disable SWAP in fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
  tags:
    - initial_role
    - disable_swap
  when: disable_swap
