---
# main.yml
# Tasks for initial role
- name: Print messages
  ansible.builtin.import_tasks: ../../../shared_tasks/print_messages.yml

- name: Users tasks
  ansible.builtin.import_tasks: users.yml

- name: Sudo tasks
  ansible.builtin.import_tasks: sudo.yml

- name: SSH tasks
  ansible.builtin.import_tasks: ssh.yml

- name: Update tasks
  ansible.builtin.import_tasks: update_apt.yml

- name: Stop UFW service
  ansible.builtin.service:
    name: ufw
    state: stopped
    enabled: false
  tags:
    - initial_role
    - firewall

- name: Set timezone to "{{ timezone }}"
  community.general.timezone:
    name: "{{ timezone }}"
  tags:
    - initial_role
    - set_timezone

- name: Ensure journalctl will not eat whole disk
  ansible.builtin.replace:
    path: /etc/systemd/journald.conf
    regexp: '^#SystemMaxUse.*'
    replace: "{{ ('SystemMaxUse=' + journalctl_max_disk_usage) }}"
    backup: true
  notify:
    - Restart journald
  tags:
    - initial_role
    - journalctl

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}.{{ domain_name }}"
    use: systemd
  tags:
    - initial_role
    - set_hostname

- name: Ensure /etc/hostname is updated
  ansible.builtin.lineinfile:
    path: /etc/hostname
    line: "{{ inventory_hostname }}.{{ domain_name }}"
    backup: true
  tags:
    - initial_role
    - set_hostname

- name: Ensure /etc/hosts is updated
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1 {{ inventory_hostname }} {{ inventory_hostname }}.{{ domain_name }}"
    backup: true
  tags:
    - initial_role
    - set_hostname

# - name: Add or update /etc/hosts entry
#   ansible.builtin.lineinfile:
#     path: /etc/hosts
#     state: present
#     regexp: "^{{ hostvars[item].ansible_host }} "
#     line: "{{ hostvars[item].ansible_host }} {{ item }}"
#     backup: true
#   loop: "{{ groups['all'] }}"

- name: Reboot
  ansible.builtin.import_tasks: reboot.yml
