---
# Tasks for initial role
- name: Print startup messages 
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop:
    - "{{ initial_message }}"
    - "{{ startup_message }}" 
  tags:
    - initial_role

- name: Ensure the user exists
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    state: present
    create_home: yes
  tags:
    - initial_role

- name: Add SSH key to the user's authorized_keys
  ansible.builtin.authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ ansible_public_key }}"
    state: present
  tags:
    - initial_role

- name: Update package cache and install useful packages
  ansible.builtin.apt:
    name: "{{ useful_packages }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - initial_role

- name: Update all packages
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - initial_role
  when: update_packages
