---
# roles/initial/tasks/main.yml
# Tasks for initial role
- name: Print messages
  ansible.builtin.import_tasks: ../../../shared_tasks/print_messages.yml

- name: Users tasks
  ansible.builtin.import_tasks: users.yml

- name: Sudo tasks
  ansible.builtin.import_tasks: sudo.yml

- name: SSH tasks
  ansible.builtin.import_tasks: ssh.yml

- name: Update tasks
  ansible.builtin.import_tasks: update_apt.yml

- name: Stop UFW service
  ansible.builtin.service:
    name: ufw
    state: stopped
    enabled: false
  tags:
    - initial_role
    - firewall

- name: Set timezone to "{{ timezone }}"
  community.general.timezone:
    name: "{{ timezone }}"
  tags:
    - initial_role
    - set_timezone

- name: Ensure journalctl will not eat whole disk
  ansible.builtin.replace:
    path: /etc/systemd/journald.conf
    regexp: '^#SystemMaxUse.*'
    replace: "{{ ('SystemMaxUse=' + journalctl_max_disk_usage) }}"
    backup: true
  notify:
    - Restart journald
  tags:
    - initial_role
    - journalctl

- name: Set hostname
  ansible.builtin.import_tasks: hostname.yml

- name: Reboot
  ansible.builtin.import_tasks: reboot.yml
