---
# roles/initial/tasks/reboot.yml
# Tasks for reboot
- name: Check if reboot required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot a machine
  ansible.builtin.reboot:
    reboot_timeout: 30
    msg: "Rebooting machine in 5 seconds"
  when: reboot_required_file.stat.exists

