---
# roles/initial/tasks/users.yml
# user's tasks for initial role
- name: Ensure the user exists
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: present
    create_home: true
    groups: sudo
    append: true
  tags:
    - users
