---
# tasks file for elastic
- name: Print messages
  ansible.builtin.import_tasks: ../../shared_tasks/print_messages.yaml

- name: Create multiple directories with permissions 0777
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0777'
  loop:
    - "{{ docker_directory }}"
  tags:
    - cadvisor

- name: Template configuration files
  ansible.builtin.template:
    src: "{{ docker_compose }}.j2"
    dest: "{{ docker_directory }}/{{ docker_compose }}"
    owner: root
    group: root
    mode: '0644'
  notify: Restart Docker Services
  tags:
    - cadvisor

- name: Create and start services using Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ docker_directory }}"
    files:
      - "{{ docker_compose }}"
  register: output
  notify: Restart Docker Services
  tags:
    - cadvisor

- name: Debug output
  ansible.builtin.debug:
    var: output
  tags:
    - cadvisor
