---
# tasks file for elastic
- name: Print messages
  ansible.builtin.import_tasks: ../../shared_tasks/print_messages.yaml

- name: Set vm.max_map_count
  ansible.posix.sysctl:
    name: "vm.max_map_count"
    value: "262144"
    sysctl_set: true
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/90-elastic.conf
  tags:
    - sysctl

- name: Create multiple directories with permissions 0777
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0777'
  loop:
    - "{{ docker_directory }}"
    - "{{ docker_directory }}/data"
    - "{{ docker_directory }}/logs"
  tags:
    - elastic

- name: Template configuration files
  ansible.builtin.template:
    src: "{{ docker_compose }}.j2"
    dest: "{{ docker_directory }}/{{ docker_compose }}"
    owner: root
    group: root
    mode: '0644'
  notify: Restart Docker Services
  tags:
    - elastic

- name: Copy configuration files
  ansible.builtin.copy:
    src: "kibana.yml"
    dest: "{{ docker_directory }}/kibana.yml"
    owner: root
    group: root
    mode: '0644'
  notify: Restart Docker Services
  tags:
    - elastic

- name: Create and start services using Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ docker_directory }}"
    files:
      - "{{ docker_compose }}"
  register: output
  tags:
    - elastic

- name: Debug output
  ansible.builtin.debug:
    var: output
  tags:
    - elastic

- name: Check if Elasticsearch is running
  ansible.builtin.uri:
    url: "http://localhost:9200/_cluster/health"
    method: GET
    status_code: 200
  register: es_health
  tags:
    - elastic

- name: Debug Elasticsearch health status
  ansible.builtin.debug:
    var: es_health
  tags:
    - elastic

- name: Add data to Elasticsearch
  ansible.builtin.uri:
    url: "http://localhost:9200/my_index/_doc/1"
    method: POST
    body: |
      {
        "name": "John Doe",
        "age": 30,
        "email": "john.doe@example.com"
      }
    body_format: json
    headers:
      Content-Type: "application/json"
    status_code: [200, 201, 204]
  when: es_health.status == 200
  register: es_add_data
  tags:
    - elastic

- name: Debug Elasticsearch add data response
  ansible.builtin.debug:
    var: es_add_data
  tags:
    - elastic

- name: Retrieve data from Elasticsearch index
  ansible.builtin.uri:
    url: "http://localhost:9200/my_index/_search"
    method: GET
    status_code: 200
  when: es_health.status == 200
  register: es_data
  tags:
    - elastic

- name: Debug Elasticsearch retrieved data
  ansible.builtin.debug:
    var: es_data
  tags:
    - elastic
