---
- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: rancher-stable
    repo_url: "https://releases.rancher.com/server-charts/stable"

- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: "https://charts.jetstack.io"

- name: Deploy latest version of cert-manager chart
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    create_namespace: true
    update_repo_cache: true
    chart_version: v1.15.1
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
    values:
      crds:
        enabled: true

- name: Wait until cert-manager is up
  kubernetes.core.k8s_info:
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
    api_version: v1
    kind: Pod
    namespace: cert-manager
  register: pod_list
  until: pod_list|json_query('resources[*].status.phase')|unique == ["Running"]

# - name: Deploy latest version of Prometheus chart inside monitoring namespace (and create it)
#  kubernetes.core.helm:
#    name: rancher
#    chart_ref: rancher-stable/rancher
#    release_namespace: cattle-system
#    create_namespace: true
#    update_repo_cache: true
#    chart_version: 2.6.8
#    values:
#      hostname:
#        rancher.home.lab
#      bootstrapPassword:
#        admin
