---
# tasks file for rke
- name: Print messages
  ansible.builtin.import_tasks: ../../../shared_tasks/print_messages.yml
  tags: preinstall

- name: Disable swap
  ansible.builtin.import_tasks: disable_swap.yml
  tags: preinstall

- name: Set sysctl
  ansible.builtin.import_tasks: sysctl.yml
  tags: preinstall

- name: Set k8s-utils
  ansible.builtin.import_tasks: k8s_utils.yml
  delegate_to: localhost
  run_once: true
  tags: preinstall

- name: Set rke cluster
  ansible.builtin.import_tasks: rke_cluster.yml
  delegate_to: localhost
  run_once: true
  tags: rke_cluster_install

- name: Set rancher cluster
  ansible.builtin.import_tasks: rancher.yml
  delegate_to: localhost
  run_once: true
  tags: rke_cluster_install

